export const experience = [
  {
    position: 'Full Stack Software Engineer',
    company: 'Rival Games',
    logo: '/rival-badge.png',
    slug: 'rival',
    timeRange: 'Feb. 2022 - Present',
    description: [
      'Developed web pages and features for RivalGames.com, an admin portal, and other private sites for the company, all with CI/CD practices',
      'Designed and developed full-stack features, from initial concept to full-scale production implementation',
      'Front-end development (React, Next): Designed and implemented responsive, modern webpages from the ground-up; created forms, modals, reusable components, etc.; implemented SSR and ISR',
      'Back-end development (Node, Express): REST API, cron services, OAuth, integrations, caching Technologies: React, Next, SWR, Node, Express, Sequelize, PostgreSQL, Formik, styled-components, SWR, Axios, Playwright, Pusher, Reddis',
      'Integrations: Stripe, Uploadcare, Discord, OAuth',
    ],
  },
  {
    position: 'Software Engineer II',
    company: 'Special Aerospace Services',
    logo: '/sas.png',
    slug: 'sas',
    timeRange: 'May 2018 - Feb. 2022',
    description: [
      'Highest position: Software tools developer under contract with Sierra Nevada Corporation (SNC)',
      'Developing Python tools/programs - back-ends and GUIs (PyQt) under controlled Agile environment',
      'Web development (Node.js, Express.js, Bootstrap)',
      'Database management (MariaDB/MySQL)',
      'Linux (CentOS) server administration and configuration',
      'Promoted to Lead of the unit testing team after one year of internship (during school), and six months of full-time employment. Managed team progress, metrics, and served as an important resource to the newer unit testers.',
      'Wrote numerous Python tools, including tools to automatically regression-test all previous test harnesses on new code builds',
      'Performed unit-level testing of United Launch Alliance (ULA) launch vehicle flight software across multiple programs and product lines, including Common Avionics, Commercial Crew Program, Interim Cryogenic Propulsion Stage, and Vulcan.',
      'Used LDRA Testbed tool suite in combination with Eclipse in a Linux environment',
      'Developed test cases based on launch vehicle flight software requirements (requirements-driven testing), and in accordance with DO-178 standards, including MC/DC coverage',
      'Gained extensive knowledge of the Ada programming language, Tartan Ada compiler suite, and MIL-STD-1750a assembly',
    ],
  },
  {
    position: 'Intern',
    company: 'Coloplast',
    logo: '/coloplast.png',
    slug: 'coloplast',
    timeRange: 'Summer 2016',
    description: [
      'Wrote various scripts to rename and organize files',
      'Analyzed documentation',
      'Various other tasks',
    ],
  },
];

export const webSkills = [
  { name: 'Javascript', icon: 'js.png' },
  { name: 'React.js', logo: '/logos/react.png' },
  { name: 'Next.js', logo: '/logos/next.svg' },
  { name: 'Node.js', logo: '/logos/node.svg' },
  { name: 'Express.js', logo: '/logos/express.svg' },
  { name: 'Sequelize.js', logo: '/logos/sequelize.svg' },
  { name: 'styled-components', logo: '/logos/styled-components.png' },
  { name: 'OAuth', icon: 'oauth.svg' },
  { name: 'SWR', logo: '/logos/swr.svg' },
  { name: 'PostgreSQL', logo: '/logos/postgres.svg' },
  { name: 'MariaDB', logo: '/logos/mariadb.svg' },
  { name: 'MySQL', logo: '/logos/mysql.svg' },
  { name: 'Playwright.js', logo: '/logos/playwright.webp' },
  { name: 'HTML', logo: '/logos/html.svg' },
  { name: 'CSS', logo: '/logos/css.svg' },
];

export const otherSkills = [
  { name: 'Python', logo: '/logos/css.svg' },
  { name: 'C/C++', logo: '/logos/css.svg' },
  { name: 'Unix', logo: '/logos/css.svg' },
  { name: 'Bash', logo: '/logos/css.svg' },
  { name: 'MATLAB', logo: '/logos/css.svg' },
  { name: 'Excel/VBA', logo: '/logos/css.svg' },
  { name: 'XML', logo: '/logos/css.svg' },
  { name: 'Mathematica', logo: '/logos/css.svg' },
  { name: 'Agile', logo: '/logos/css.svg' },
  { name: 'JIRA', logo: '/logos/css.svg' },
  { name: 'Ada', logo: '/logos/css.svg' },
  { name: 'multi-threaded programming', logo: '/logos/css.svg' },
];
