import Head from 'next/head';
import 'styles/globals.css';
import Layout from '../Layout';

export default function App(props) {
  return (
    <>
      <Head>
        <title>Danny Langevin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout {...props} />
    </>
  );
}
